import type { CategoryId } from '../src/lib/types.js';

/**
 * 추적 대상 소프트웨어 카탈로그.
 *
 * 새 제품을 추가하려면 이 배열에 한 줄 추가하면 끝이다.
 *  - `eol`    : endoflife.date 제품 slug (https://endoflife.date/api/v1/products 참고)
 *  - `repo`   : GitHub `owner/name` — Releases API로 최신 릴리즈/릴리즈 노트를 가져온다
 *  - 둘 중 하나만 있어도 동작한다. 둘 다 있으면 endoflife.date를 EOL 기준으로,
 *    GitHub를 릴리즈 노트/프리릴리즈 판별 보강용으로 쓴다.
 *  - `cpe`    : NVD CVE 조회용 CPE. endoflife.date가 CPE 식별자를 주면 자동으로 잡히므로
 *              여기 적을 필요가 없고, 없을 때만 수동으로 채운다.
 *              (검색: https://services.nvd.nist.gov/rest/json/cpes/2.0?keywordSearch=…)
 *  - `policy` : 제품별 도입 정책 오버라이드 (미지정 시 scripts/verdict.ts 기본값)
 *
 * `blurb`는 화면에 그대로 나가므로 사이트 표기 언어(영문)로 적는다.
 */
export interface CatalogEntry {
  id: string;
  name: string;
  category: CategoryId;
  vendor: string;
  blurb: string;
  homepage: string;
  /** simple-icons slug (아이콘 폴백용) */
  icon?: string;
  eol?: string;
  repo?: string;
  /** endoflife.date가 CPE를 주지 않는 제품용 수동 매핑 */
  cpe?: string;
  /** GitHub 태그 중 이 정규식에 맞는 것만 릴리즈로 인정 */
  tagFilter?: string;
  policy?: {
    /** 새 마이너 트레인을 도입 가능으로 볼 때까지 필요한 최소 숙성일 */
    minSoakDays?: number;
    /** 도입 가능으로 볼 최소 패치 번호 (x.y.Z 의 Z) */
    minPatch?: number;
    /** EOL 잔여일이 이보다 짧으면 신규 도입 부적합 */
    eolWarnDays?: number;
  };
}

export const CATALOG: CatalogEntry[] = [
  // ─────────────────────────────── Containers & Orchestration
  {
    id: 'kubernetes',
    name: 'Kubernetes',
    category: 'container',
    vendor: 'CNCF',
    blurb: 'Container orchestration standard',
    homepage: 'https://kubernetes.io',
    icon: 'kubernetes',
    eol: 'kubernetes',
    repo: 'kubernetes/kubernetes',
    policy: { minSoakDays: 60, minPatch: 3, eolWarnDays: 120 },
  },
  {
    id: 'containerd',
    name: 'containerd',
    category: 'container',
    vendor: 'CNCF',
    blurb: 'Container runtime',
    homepage: 'https://containerd.io',
    icon: 'containerd',
    eol: 'containerd',
    repo: 'containerd/containerd',
  },
  {
    id: 'docker-engine',
    name: 'Docker Engine',
    category: 'container',
    vendor: 'Docker',
    blurb: 'Container engine (moby)',
    homepage: 'https://docs.docker.com/engine/',
    icon: 'docker',
    eol: 'docker-engine',
    repo: 'moby/moby',
  },
  {
    id: 'helm',
    name: 'Helm',
    category: 'container',
    vendor: 'CNCF',
    blurb: 'Kubernetes package manager',
    homepage: 'https://helm.sh',
    icon: 'helm',
    repo: 'helm/helm',
    cpe: 'cpe:2.3:a:helm:helm',
  },
  {
    id: 'argo-cd',
    name: 'Argo CD',
    category: 'container',
    vendor: 'CNCF',
    blurb: 'GitOps continuous delivery',
    homepage: 'https://argo-cd.readthedocs.io',
    icon: 'argo',
    eol: 'argo-cd',
    repo: 'argoproj/argo-cd',
    cpe: 'cpe:2.3:a:linuxfoundation:argo-cd',
  },
  {
    id: 'argo-workflows',
    name: 'Argo Workflows',
    category: 'container',
    vendor: 'CNCF',
    blurb: 'Kubernetes-native workflow engine',
    homepage: 'https://argo-workflows.readthedocs.io',
    icon: 'argo',
    eol: 'argo-workflows',
    repo: 'argoproj/argo-workflows',
    cpe: 'cpe:2.3:a:linuxfoundation:argo-workflows',
  },
  {
    id: 'istio',
    name: 'Istio',
    category: 'container',
    vendor: 'CNCF',
    blurb: 'Service mesh',
    homepage: 'https://istio.io',
    icon: 'istio',
    eol: 'istio',
    repo: 'istio/istio',
  },
  {
    id: 'harbor',
    name: 'Harbor',
    category: 'container',
    vendor: 'CNCF',
    blurb: 'Container image registry',
    homepage: 'https://goharbor.io',
    icon: 'harbor',
    eol: 'harbor',
    repo: 'goharbor/harbor',
  },
  {
    id: 'etcd',
    name: 'etcd',
    category: 'container',
    vendor: 'CNCF',
    blurb: 'Distributed key-value store behind Kubernetes state',
    homepage: 'https://etcd.io',
    icon: 'etcd',
    eol: 'etcd',
    repo: 'etcd-io/etcd',
    cpe: 'cpe:2.3:a:etcd:etcd',
    policy: { minSoakDays: 45, minPatch: 2 },
  },
  {
    id: 'cert-manager',
    name: 'cert-manager',
    category: 'container',
    vendor: 'CNCF',
    blurb: 'Certificate automation for Kubernetes',
    homepage: 'https://cert-manager.io',
    eol: 'cert-manager',
    repo: 'cert-manager/cert-manager',
    cpe: 'cpe:2.3:a:linuxfoundation:cert-manager',
  },
  {
    id: 'traefik',
    name: 'Traefik',
    category: 'container',
    vendor: 'Traefik Labs',
    blurb: 'Cloud-native reverse proxy and ingress',
    homepage: 'https://traefik.io',
    icon: 'traefikproxy',
    eol: 'traefik',
    repo: 'traefik/traefik',
  },
  {
    id: 'envoy',
    name: 'Envoy',
    category: 'container',
    vendor: 'CNCF',
    blurb: 'L7 proxy and service mesh data plane',
    homepage: 'https://www.envoyproxy.io',
    icon: 'envoyproxy',
    eol: 'envoy',
    repo: 'envoyproxy/envoy',
  },
  {
    id: 'podman',
    name: 'Podman',
    category: 'container',
    vendor: 'Red Hat',
    blurb: 'Daemonless container engine',
    homepage: 'https://podman.io',
    icon: 'podman',
    eol: 'podman',
    repo: 'containers/podman',
  },
  {
    id: 'flux',
    name: 'Flux CD',
    category: 'container',
    vendor: 'CNCF',
    blurb: 'GitOps toolkit',
    homepage: 'https://fluxcd.io',
    icon: 'flux',
    eol: 'flux',
    repo: 'fluxcd/flux2',
  },

  // ─────────────────────────────── IaC & CI/CD
  {
    id: 'terraform',
    name: 'Terraform',
    category: 'iac-cicd',
    vendor: 'HashiCorp',
    blurb: 'Infrastructure-as-code provisioning',
    homepage: 'https://www.terraform.io',
    icon: 'terraform',
    eol: 'terraform',
    repo: 'hashicorp/terraform',
    policy: { minSoakDays: 30, minPatch: 1 },
  },
  {
    id: 'opentofu',
    name: 'OpenTofu',
    category: 'iac-cicd',
    vendor: 'Linux Foundation',
    blurb: 'Open-source Terraform fork',
    homepage: 'https://opentofu.org',
    icon: 'opentofu',
    eol: 'opentofu',
    repo: 'opentofu/opentofu',
  },
  {
    id: 'ansible-core',
    name: 'Ansible Core',
    category: 'iac-cicd',
    vendor: 'Red Hat',
    blurb: 'Agentless configuration management',
    homepage: 'https://docs.ansible.com',
    icon: 'ansible',
    eol: 'ansible-core',
    repo: 'ansible/ansible',
  },
  {
    id: 'jenkins',
    name: 'Jenkins',
    category: 'iac-cicd',
    vendor: 'CDF',
    blurb: 'CI server — prefer the LTS line',
    homepage: 'https://www.jenkins.io',
    icon: 'jenkins',
    eol: 'jenkins',
    repo: 'jenkinsci/jenkins',
    policy: { minSoakDays: 21 },
  },
  {
    id: 'gitlab',
    name: 'GitLab',
    category: 'iac-cicd',
    vendor: 'GitLab Inc.',
    blurb: 'Self-managed DevOps platform',
    homepage: 'https://about.gitlab.com',
    icon: 'gitlab',
    eol: 'gitlab',
  },
  {
    id: 'gitlab-runner',
    name: 'GitLab Runner',
    category: 'iac-cicd',
    vendor: 'GitLab Inc.',
    blurb: 'GitLab CI job executor',
    homepage: 'https://docs.gitlab.com/runner/',
    icon: 'gitlab',
    eol: 'gitlab-runner',
  },
  {
    id: 'actions-runner',
    name: 'GitHub Actions Runner',
    category: 'iac-cicd',
    vendor: 'GitHub',
    blurb: 'Self-hosted runner agent',
    homepage: 'https://github.com/actions/runner',
    icon: 'githubactions',
    repo: 'actions/runner',
    cpe: 'cpe:2.3:a:github:runner',
  },
  {
    id: 'vault',
    name: 'HashiCorp Vault',
    category: 'iac-cicd',
    vendor: 'HashiCorp',
    blurb: 'Secrets management',
    homepage: 'https://www.vaultproject.io',
    icon: 'vault',
    eol: 'hashicorp-vault',
    repo: 'hashicorp/vault',
    policy: { minSoakDays: 30, eolWarnDays: 120 },
  },
  {
    id: 'consul',
    name: 'Consul',
    category: 'iac-cicd',
    vendor: 'HashiCorp',
    blurb: 'Service discovery and service mesh',
    homepage: 'https://www.consul.io',
    icon: 'consul',
    eol: 'consul',
    repo: 'hashicorp/consul',
  },
  {
    id: 'nomad',
    name: 'Nomad',
    category: 'iac-cicd',
    vendor: 'HashiCorp',
    blurb: 'Workload orchestrator',
    homepage: 'https://www.nomadproject.io',
    icon: 'nomad',
    eol: 'nomad',
    repo: 'hashicorp/nomad',
  },
  {
    id: 'packer',
    name: 'Packer',
    category: 'iac-cicd',
    vendor: 'HashiCorp',
    blurb: 'Machine image builder',
    homepage: 'https://www.packer.io',
    icon: 'packer',
    eol: 'hashicorp-packer',
    repo: 'hashicorp/packer',
  },
  {
    id: 'sonarqube',
    name: 'SonarQube Community',
    category: 'iac-cicd',
    vendor: 'Sonar',
    blurb: 'Static analysis and quality gates',
    homepage: 'https://www.sonarsource.com',
    icon: 'sonarqube',
    eol: 'sonarqube-community',
    repo: 'SonarSource/sonarqube',
  },
  {
    id: 'keycloak',
    name: 'Keycloak',
    category: 'iac-cicd',
    vendor: 'CNCF',
    blurb: 'Identity and access management',
    homepage: 'https://www.keycloak.org',
    icon: 'keycloak',
    eol: 'keycloak',
    repo: 'keycloak/keycloak',
  },
  {
    id: 'tekton',
    name: 'Tekton Pipelines',
    category: 'iac-cicd',
    vendor: 'CDF',
    blurb: 'Kubernetes-native CI/CD',
    homepage: 'https://tekton.dev',
    icon: 'tekton',
    repo: 'tektoncd/pipeline',
    cpe: 'cpe:2.3:a:linuxfoundation:tekton_pipelines',
  },

  // ─────────────────────────────── Observability
  {
    id: 'prometheus',
    name: 'Prometheus',
    category: 'observability',
    vendor: 'CNCF',
    blurb: 'Metrics collection and time-series database',
    homepage: 'https://prometheus.io',
    icon: 'prometheus',
    eol: 'prometheus',
    repo: 'prometheus/prometheus',
  },
  {
    id: 'grafana',
    name: 'Grafana',
    category: 'observability',
    vendor: 'Grafana Labs',
    blurb: 'Observability dashboards',
    homepage: 'https://grafana.com',
    icon: 'grafana',
    eol: 'grafana',
    repo: 'grafana/grafana',
  },
  {
    id: 'loki',
    name: 'Grafana Loki',
    category: 'observability',
    vendor: 'Grafana Labs',
    blurb: 'Log aggregation',
    homepage: 'https://grafana.com/oss/loki/',
    icon: 'grafana',
    eol: 'grafana-loki',
    repo: 'grafana/loki',
  },
  {
    id: 'otel-collector',
    name: 'OpenTelemetry Collector',
    category: 'observability',
    vendor: 'CNCF',
    blurb: 'Telemetry ingest pipeline',
    homepage: 'https://opentelemetry.io',
    icon: 'opentelemetry',
    repo: 'open-telemetry/opentelemetry-collector',
  },
  {
    id: 'elasticsearch',
    name: 'Elasticsearch',
    category: 'observability',
    vendor: 'Elastic',
    blurb: 'Search and log storage',
    homepage: 'https://www.elastic.co',
    icon: 'elasticsearch',
    eol: 'elasticsearch',
    repo: 'elastic/elasticsearch',
    policy: { minSoakDays: 45, eolWarnDays: 120 },
  },
  {
    id: 'opensearch',
    name: 'OpenSearch',
    category: 'observability',
    vendor: 'Linux Foundation',
    blurb: 'Open-source Elasticsearch fork',
    homepage: 'https://opensearch.org',
    icon: 'opensearch',
    eol: 'opensearch',
    repo: 'opensearch-project/OpenSearch',
  },
  {
    id: 'fluent-bit',
    name: 'Fluent Bit',
    category: 'observability',
    vendor: 'CNCF',
    blurb: 'Lightweight log and metric processor',
    homepage: 'https://fluentbit.io',
    icon: 'fluentbit',
    eol: 'fluent-bit',
    repo: 'fluent/fluent-bit',
    cpe: 'cpe:2.3:a:treasuredata:fluent_bit',
  },
  {
    id: 'thanos',
    name: 'Thanos',
    category: 'observability',
    vendor: 'CNCF',
    blurb: 'Long-term storage and global query for Prometheus',
    homepage: 'https://thanos.io',
    repo: 'thanos-io/thanos',
  },
  {
    id: 'vector',
    name: 'Vector',
    category: 'observability',
    vendor: 'Datadog',
    blurb: 'High-throughput observability pipeline',
    homepage: 'https://vector.dev',
    repo: 'vectordotdev/vector',
  },
  {
    id: 'jaeger',
    name: 'Jaeger',
    category: 'observability',
    vendor: 'CNCF',
    blurb: 'Distributed tracing',
    homepage: 'https://www.jaegertracing.io',
    icon: 'jaeger',
    repo: 'jaegertracing/jaeger',
  },

  // ─────────────────────────────── Runtimes, Middleware & Databases
  {
    id: 'nodejs',
    name: 'Node.js',
    category: 'runtime',
    vendor: 'OpenJS Foundation',
    blurb: 'JavaScript runtime — even majors are LTS',
    homepage: 'https://nodejs.org',
    icon: 'nodedotjs',
    eol: 'nodejs',
    repo: 'nodejs/node',
  },
  {
    id: 'python',
    name: 'Python',
    category: 'runtime',
    vendor: 'PSF',
    blurb: 'General-purpose runtime',
    homepage: 'https://www.python.org',
    icon: 'python',
    eol: 'python',
    repo: 'python/cpython',
    tagFilter: '^v?\\d+\\.\\d+\\.\\d+$',
  },
  {
    id: 'go',
    name: 'Go',
    category: 'runtime',
    vendor: 'Google',
    blurb: 'Compiled language and toolchain',
    homepage: 'https://go.dev',
    icon: 'go',
    eol: 'go',
  },
  {
    id: 'temurin',
    name: 'Eclipse Temurin (JDK)',
    category: 'runtime',
    vendor: 'Adoptium',
    blurb: 'OpenJDK builds — prefer the LTS lines',
    homepage: 'https://adoptium.net',
    icon: 'eclipseadoptium',
    eol: 'eclipse-temurin',
    policy: { minSoakDays: 60, eolWarnDays: 180 },
  },
  {
    id: 'spring-boot',
    name: 'Spring Boot',
    category: 'runtime',
    vendor: 'Broadcom',
    blurb: 'JVM application framework',
    homepage: 'https://spring.io/projects/spring-boot',
    icon: 'springboot',
    eol: 'spring-boot',
    repo: 'spring-projects/spring-boot',
    cpe: 'cpe:2.3:a:vmware:spring_boot',
  },
  {
    id: 'tomcat',
    name: 'Apache Tomcat',
    category: 'runtime',
    vendor: 'ASF',
    blurb: 'Servlet container',
    homepage: 'https://tomcat.apache.org',
    icon: 'apachetomcat',
    eol: 'tomcat',
  },
  {
    id: 'postgresql',
    name: 'PostgreSQL',
    category: 'runtime',
    vendor: 'PGDG',
    blurb: 'Relational database',
    homepage: 'https://www.postgresql.org',
    icon: 'postgresql',
    eol: 'postgresql',
    policy: { minSoakDays: 90, minPatch: 1, eolWarnDays: 180 },
  },
  {
    id: 'mysql',
    name: 'MySQL',
    category: 'runtime',
    vendor: 'Oracle',
    blurb: 'Relational database',
    homepage: 'https://www.mysql.com',
    icon: 'mysql',
    eol: 'mysql',
    policy: { minSoakDays: 90, eolWarnDays: 180 },
  },
  {
    id: 'mariadb',
    name: 'MariaDB',
    category: 'runtime',
    vendor: 'MariaDB Foundation',
    blurb: 'MySQL-compatible relational database',
    homepage: 'https://mariadb.org',
    icon: 'mariadb',
    eol: 'mariadb',
    policy: { minSoakDays: 90, eolWarnDays: 180 },
  },
  {
    id: 'mongodb',
    name: 'MongoDB',
    category: 'runtime',
    vendor: 'MongoDB Inc.',
    blurb: 'Document database',
    homepage: 'https://www.mongodb.com',
    icon: 'mongodb',
    eol: 'mongodb',
    policy: { minSoakDays: 90, eolWarnDays: 180 },
  },
  {
    id: 'redis',
    name: 'Redis',
    category: 'runtime',
    vendor: 'Redis Ltd.',
    blurb: 'In-memory data store',
    homepage: 'https://redis.io',
    icon: 'redis',
    eol: 'redis',
    repo: 'redis/redis',
  },
  {
    id: 'valkey',
    name: 'Valkey',
    category: 'runtime',
    vendor: 'Linux Foundation',
    blurb: 'Open-source Redis fork',
    homepage: 'https://valkey.io',
    icon: 'valkey',
    eol: 'valkey',
    repo: 'valkey-io/valkey',
  },
  {
    id: 'kafka',
    name: 'Apache Kafka',
    category: 'runtime',
    vendor: 'ASF',
    blurb: 'Distributed event streaming',
    homepage: 'https://kafka.apache.org',
    icon: 'apachekafka',
    eol: 'apache-kafka',
    repo: 'apache/kafka',
    policy: { minSoakDays: 60, minPatch: 1 },
  },
  {
    id: 'rabbitmq',
    name: 'RabbitMQ',
    category: 'runtime',
    vendor: 'Broadcom',
    blurb: 'Message broker',
    homepage: 'https://www.rabbitmq.com',
    icon: 'rabbitmq',
    eol: 'rabbitmq',
    repo: 'rabbitmq/rabbitmq-server',
  },
  {
    id: 'nginx',
    name: 'nginx',
    category: 'runtime',
    vendor: 'F5',
    blurb: 'Web server and reverse proxy',
    homepage: 'https://nginx.org',
    icon: 'nginx',
    eol: 'nginx',
  },
  {
    id: 'haproxy',
    name: 'HAProxy',
    category: 'runtime',
    vendor: 'HAProxy Technologies',
    blurb: 'L4/L7 load balancer',
    homepage: 'https://www.haproxy.org',
    icon: 'haproxy',
    eol: 'haproxy',
    repo: 'haproxy/haproxy',
  },
  {
    id: 'minio',
    name: 'MinIO',
    category: 'runtime',
    vendor: 'MinIO Inc.',
    blurb: 'S3-compatible object storage',
    homepage: 'https://min.io',
    icon: 'minio',
    repo: 'minio/minio',
    cpe: 'cpe:2.3:a:minio:minio',
    // 날짜 기반 릴리즈 태그 (RELEASE.2026-12-18T13-15-44Z)
    tagFilter: '^RELEASE\\.',
  },
];
