import type { CategoryId } from '../src/lib/types.js';

/**
 * 추적 대상 소프트웨어 카탈로그.
 *
 * 새 제품을 추가하려면 이 배열에 한 줄 추가하면 끝이다.
 *  - `eol`    : endoflife.date 제품 slug (https://endoflife.date/api/v1/products 참고)
 *  - `repo`   : GitHub `owner/name` — Releases API로 최신 릴리즈/릴리즈 노트를 가져온다
 *  - 둘 중 하나만 있어도 동작한다. 둘 다 있으면 endoflife.date를 EOL 기준으로,
 *    GitHub를 릴리즈 노트/프리릴리즈 판별 보강용으로 쓴다.
 *  - `policy` : 제품별 도입 정책 오버라이드 (미지정 시 scripts/verdict.ts 기본값)
 */
export interface CatalogEntry {
  id: string;
  name: string;
  category: CategoryId;
  vendor: string;
  blurb: string;
  homepage: string;
  /** simple-icons slug (아이콘 폴백용) */
  icon?: string;
  eol?: string;
  repo?: string;
  /** GitHub 태그 중 이 정규식에 맞는 것만 릴리즈로 인정 */
  tagFilter?: string;
  policy?: {
    /** 새 마이너 트레인을 도입 가능으로 볼 때까지 필요한 최소 숙성일 */
    minSoakDays?: number;
    /** 도입 가능으로 볼 최소 패치 번호 (x.y.Z 의 Z) */
    minPatch?: number;
    /** EOL 잔여일이 이보다 짧으면 신규 도입 부적합 */
    eolWarnDays?: number;
  };
}

export const CATALOG: CatalogEntry[] = [
  // ─────────────────────────────── 컨테이너 / 오케스트레이션
  {
    id: 'kubernetes',
    name: 'Kubernetes',
    category: 'container',
    vendor: 'CNCF',
    blurb: '컨테이너 오케스트레이션 표준',
    homepage: 'https://kubernetes.io',
    icon: 'kubernetes',
    eol: 'kubernetes',
    repo: 'kubernetes/kubernetes',
    policy: { minSoakDays: 60, minPatch: 3, eolWarnDays: 120 },
  },
  {
    id: 'containerd',
    name: 'containerd',
    category: 'container',
    vendor: 'CNCF',
    blurb: '컨테이너 런타임',
    homepage: 'https://containerd.io',
    icon: 'containerd',
    eol: 'containerd',
    repo: 'containerd/containerd',
  },
  {
    id: 'docker-engine',
    name: 'Docker Engine',
    category: 'container',
    vendor: 'Docker',
    blurb: '컨테이너 엔진 / moby',
    homepage: 'https://docs.docker.com/engine/',
    icon: 'docker',
    eol: 'docker-engine',
    repo: 'moby/moby',
  },
  {
    id: 'helm',
    name: 'Helm',
    category: 'container',
    vendor: 'CNCF',
    blurb: '쿠버네티스 패키지 매니저',
    homepage: 'https://helm.sh',
    icon: 'helm',
    repo: 'helm/helm',
  },
  {
    id: 'argo-cd',
    name: 'Argo CD',
    category: 'container',
    vendor: 'CNCF',
    blurb: 'GitOps 지속적 배포',
    homepage: 'https://argo-cd.readthedocs.io',
    icon: 'argo',
    eol: 'argo-cd',
    repo: 'argoproj/argo-cd',
  },
  {
    id: 'argo-workflows',
    name: 'Argo Workflows',
    category: 'container',
    vendor: 'CNCF',
    blurb: '쿠버네티스 네이티브 워크플로 엔진',
    homepage: 'https://argo-workflows.readthedocs.io',
    icon: 'argo',
    eol: 'argo-workflows',
    repo: 'argoproj/argo-workflows',
  },
  {
    id: 'istio',
    name: 'Istio',
    category: 'container',
    vendor: 'CNCF',
    blurb: '서비스 메시',
    homepage: 'https://istio.io',
    icon: 'istio',
    eol: 'istio',
    repo: 'istio/istio',
  },
  {
    id: 'harbor',
    name: 'Harbor',
    category: 'container',
    vendor: 'CNCF',
    blurb: '컨테이너 이미지 레지스트리',
    homepage: 'https://goharbor.io',
    icon: 'harbor',
    eol: 'harbor',
    repo: 'goharbor/harbor',
  },
  {
    id: 'etcd',
    name: 'etcd',
    category: 'container',
    vendor: 'CNCF',
    blurb: '분산 키-값 저장소 (K8s 상태 저장)',
    homepage: 'https://etcd.io',
    icon: 'etcd',
    eol: 'etcd',
    repo: 'etcd-io/etcd',
    policy: { minSoakDays: 45, minPatch: 2 },
  },
  {
    id: 'cert-manager',
    name: 'cert-manager',
    category: 'container',
    vendor: 'CNCF',
    blurb: '쿠버네티스 인증서 자동화',
    homepage: 'https://cert-manager.io',
    eol: 'cert-manager',
    repo: 'cert-manager/cert-manager',
  },
  {
    id: 'traefik',
    name: 'Traefik',
    category: 'container',
    vendor: 'Traefik Labs',
    blurb: '클라우드 네이티브 리버스 프록시 / 인그레스',
    homepage: 'https://traefik.io',
    icon: 'traefikproxy',
    eol: 'traefik',
    repo: 'traefik/traefik',
  },
  {
    id: 'envoy',
    name: 'Envoy',
    category: 'container',
    vendor: 'CNCF',
    blurb: 'L7 프록시 / 서비스 메시 데이터플레인',
    homepage: 'https://www.envoyproxy.io',
    icon: 'envoyproxy',
    eol: 'envoy',
    repo: 'envoyproxy/envoy',
  },
  {
    id: 'podman',
    name: 'Podman',
    category: 'container',
    vendor: 'Red Hat',
    blurb: '데몬리스 컨테이너 엔진',
    homepage: 'https://podman.io',
    icon: 'podman',
    eol: 'podman',
    repo: 'containers/podman',
  },
  {
    id: 'flux',
    name: 'Flux CD',
    category: 'container',
    vendor: 'CNCF',
    blurb: 'GitOps 툴킷',
    homepage: 'https://fluxcd.io',
    icon: 'flux',
    eol: 'flux',
    repo: 'fluxcd/flux2',
  },

  // ─────────────────────────────── IaC / CI·CD
  {
    id: 'terraform',
    name: 'Terraform',
    category: 'iac-cicd',
    vendor: 'HashiCorp',
    blurb: 'IaC 프로비저닝',
    homepage: 'https://www.terraform.io',
    icon: 'terraform',
    eol: 'terraform',
    repo: 'hashicorp/terraform',
    policy: { minSoakDays: 30, minPatch: 1 },
  },
  {
    id: 'opentofu',
    name: 'OpenTofu',
    category: 'iac-cicd',
    vendor: 'Linux Foundation',
    blurb: 'Terraform 오픈소스 포크',
    homepage: 'https://opentofu.org',
    icon: 'opentofu',
    eol: 'opentofu',
    repo: 'opentofu/opentofu',
  },
  {
    id: 'ansible-core',
    name: 'Ansible Core',
    category: 'iac-cicd',
    vendor: 'Red Hat',
    blurb: '에이전트리스 구성 관리',
    homepage: 'https://docs.ansible.com',
    icon: 'ansible',
    eol: 'ansible-core',
    repo: 'ansible/ansible',
  },
  {
    id: 'jenkins',
    name: 'Jenkins',
    category: 'iac-cicd',
    vendor: 'CDF',
    blurb: 'CI 서버 (LTS 라인 권장)',
    homepage: 'https://www.jenkins.io',
    icon: 'jenkins',
    eol: 'jenkins',
    repo: 'jenkinsci/jenkins',
    policy: { minSoakDays: 21 },
  },
  {
    id: 'gitlab',
    name: 'GitLab',
    category: 'iac-cicd',
    vendor: 'GitLab Inc.',
    blurb: 'DevOps 플랫폼 (self-managed)',
    homepage: 'https://about.gitlab.com',
    icon: 'gitlab',
    eol: 'gitlab',
  },
  {
    id: 'gitlab-runner',
    name: 'GitLab Runner',
    category: 'iac-cicd',
    vendor: 'GitLab Inc.',
    blurb: 'GitLab CI 잡 실행기',
    homepage: 'https://docs.gitlab.com/runner/',
    icon: 'gitlab',
    eol: 'gitlab-runner',
  },
  {
    id: 'actions-runner',
    name: 'GitHub Actions Runner',
    category: 'iac-cicd',
    vendor: 'GitHub',
    blurb: '셀프 호스티드 러너',
    homepage: 'https://github.com/actions/runner',
    icon: 'githubactions',
    repo: 'actions/runner',
  },
  {
    id: 'vault',
    name: 'HashiCorp Vault',
    category: 'iac-cicd',
    vendor: 'HashiCorp',
    blurb: '시크릿 관리',
    homepage: 'https://www.vaultproject.io',
    icon: 'vault',
    eol: 'hashicorp-vault',
    repo: 'hashicorp/vault',
    policy: { minSoakDays: 30, eolWarnDays: 120 },
  },
  {
    id: 'consul',
    name: 'Consul',
    category: 'iac-cicd',
    vendor: 'HashiCorp',
    blurb: '서비스 디스커버리 / 서비스 메시',
    homepage: 'https://www.consul.io',
    icon: 'consul',
    eol: 'consul',
    repo: 'hashicorp/consul',
  },
  {
    id: 'nomad',
    name: 'Nomad',
    category: 'iac-cicd',
    vendor: 'HashiCorp',
    blurb: '워크로드 오케스트레이터',
    homepage: 'https://www.nomadproject.io',
    icon: 'nomad',
    eol: 'nomad',
    repo: 'hashicorp/nomad',
  },
  {
    id: 'packer',
    name: 'Packer',
    category: 'iac-cicd',
    vendor: 'HashiCorp',
    blurb: '머신 이미지 빌더',
    homepage: 'https://www.packer.io',
    icon: 'packer',
    eol: 'hashicorp-packer',
    repo: 'hashicorp/packer',
  },
  {
    id: 'sonarqube',
    name: 'SonarQube Community',
    category: 'iac-cicd',
    vendor: 'Sonar',
    blurb: '정적 분석 / 코드 품질 게이트',
    homepage: 'https://www.sonarsource.com',
    icon: 'sonarqube',
    eol: 'sonarqube-community',
    repo: 'SonarSource/sonarqube',
  },
  {
    id: 'keycloak',
    name: 'Keycloak',
    category: 'iac-cicd',
    vendor: 'CNCF',
    blurb: 'IAM / SSO',
    homepage: 'https://www.keycloak.org',
    icon: 'keycloak',
    eol: 'keycloak',
    repo: 'keycloak/keycloak',
  },
  {
    id: 'tekton',
    name: 'Tekton Pipelines',
    category: 'iac-cicd',
    vendor: 'CDF',
    blurb: '쿠버네티스 네이티브 CI/CD',
    homepage: 'https://tekton.dev',
    icon: 'tekton',
    repo: 'tektoncd/pipeline',
  },

  // ─────────────────────────────── 관측 / 모니터링
  {
    id: 'prometheus',
    name: 'Prometheus',
    category: 'observability',
    vendor: 'CNCF',
    blurb: '메트릭 수집 / 시계열 DB',
    homepage: 'https://prometheus.io',
    icon: 'prometheus',
    eol: 'prometheus',
    repo: 'prometheus/prometheus',
  },
  {
    id: 'grafana',
    name: 'Grafana',
    category: 'observability',
    vendor: 'Grafana Labs',
    blurb: '관측 대시보드',
    homepage: 'https://grafana.com',
    icon: 'grafana',
    eol: 'grafana',
    repo: 'grafana/grafana',
  },
  {
    id: 'loki',
    name: 'Grafana Loki',
    category: 'observability',
    vendor: 'Grafana Labs',
    blurb: '로그 집계',
    homepage: 'https://grafana.com/oss/loki/',
    icon: 'grafana',
    eol: 'grafana-loki',
    repo: 'grafana/loki',
  },
  {
    id: 'otel-collector',
    name: 'OpenTelemetry Collector',
    category: 'observability',
    vendor: 'CNCF',
    blurb: '텔레메트리 수집 파이프라인',
    homepage: 'https://opentelemetry.io',
    icon: 'opentelemetry',
    repo: 'open-telemetry/opentelemetry-collector',
  },
  {
    id: 'elasticsearch',
    name: 'Elasticsearch',
    category: 'observability',
    vendor: 'Elastic',
    blurb: '검색 / 로그 저장소',
    homepage: 'https://www.elastic.co',
    icon: 'elasticsearch',
    eol: 'elasticsearch',
    repo: 'elastic/elasticsearch',
    policy: { minSoakDays: 45, eolWarnDays: 120 },
  },
  {
    id: 'opensearch',
    name: 'OpenSearch',
    category: 'observability',
    vendor: 'Linux Foundation',
    blurb: 'Elasticsearch 오픈소스 포크',
    homepage: 'https://opensearch.org',
    icon: 'opensearch',
    eol: 'opensearch',
    repo: 'opensearch-project/OpenSearch',
  },
  {
    id: 'fluent-bit',
    name: 'Fluent Bit',
    category: 'observability',
    vendor: 'CNCF',
    blurb: '경량 로그 / 메트릭 프로세서',
    homepage: 'https://fluentbit.io',
    icon: 'fluentbit',
    eol: 'fluent-bit',
    repo: 'fluent/fluent-bit',
  },
  {
    id: 'thanos',
    name: 'Thanos',
    category: 'observability',
    vendor: 'CNCF',
    blurb: 'Prometheus 장기 보관 / 글로벌 쿼리',
    homepage: 'https://thanos.io',
    repo: 'thanos-io/thanos',
  },
  {
    id: 'vector',
    name: 'Vector',
    category: 'observability',
    vendor: 'Datadog',
    blurb: '고성능 옵저버빌리티 파이프라인',
    homepage: 'https://vector.dev',
    repo: 'vectordotdev/vector',
  },
  {
    id: 'jaeger',
    name: 'Jaeger',
    category: 'observability',
    vendor: 'CNCF',
    blurb: '분산 트레이싱',
    homepage: 'https://www.jaegertracing.io',
    icon: 'jaeger',
    repo: 'jaegertracing/jaeger',
  },

  // ─────────────────────────────── 런타임 / 미들웨어 / DB
  {
    id: 'nodejs',
    name: 'Node.js',
    category: 'runtime',
    vendor: 'OpenJS Foundation',
    blurb: 'JS 런타임 (짝수 메이저 = LTS)',
    homepage: 'https://nodejs.org',
    icon: 'nodedotjs',
    eol: 'nodejs',
    repo: 'nodejs/node',
  },
  {
    id: 'python',
    name: 'Python',
    category: 'runtime',
    vendor: 'PSF',
    blurb: '범용 런타임',
    homepage: 'https://www.python.org',
    icon: 'python',
    eol: 'python',
    repo: 'python/cpython',
    tagFilter: '^v?\\d+\\.\\d+\\.\\d+$',
  },
  {
    id: 'go',
    name: 'Go',
    category: 'runtime',
    vendor: 'Google',
    blurb: '컴파일 언어 / 툴체인',
    homepage: 'https://go.dev',
    icon: 'go',
    eol: 'go',
  },
  {
    id: 'temurin',
    name: 'Eclipse Temurin (JDK)',
    category: 'runtime',
    vendor: 'Adoptium',
    blurb: 'OpenJDK 빌드 (LTS 라인 권장)',
    homepage: 'https://adoptium.net',
    icon: 'eclipseadoptium',
    eol: 'eclipse-temurin',
    policy: { minSoakDays: 60, eolWarnDays: 180 },
  },
  {
    id: 'spring-boot',
    name: 'Spring Boot',
    category: 'runtime',
    vendor: 'Broadcom',
    blurb: 'JVM 애플리케이션 프레임워크',
    homepage: 'https://spring.io/projects/spring-boot',
    icon: 'springboot',
    eol: 'spring-boot',
    repo: 'spring-projects/spring-boot',
  },
  {
    id: 'tomcat',
    name: 'Apache Tomcat',
    category: 'runtime',
    vendor: 'ASF',
    blurb: '서블릿 컨테이너 / WAS',
    homepage: 'https://tomcat.apache.org',
    icon: 'apachetomcat',
    eol: 'tomcat',
  },
  {
    id: 'postgresql',
    name: 'PostgreSQL',
    category: 'runtime',
    vendor: 'PGDG',
    blurb: '관계형 DB',
    homepage: 'https://www.postgresql.org',
    icon: 'postgresql',
    eol: 'postgresql',
    policy: { minSoakDays: 90, minPatch: 1, eolWarnDays: 180 },
  },
  {
    id: 'mysql',
    name: 'MySQL',
    category: 'runtime',
    vendor: 'Oracle',
    blurb: '관계형 DB',
    homepage: 'https://www.mysql.com',
    icon: 'mysql',
    eol: 'mysql',
    policy: { minSoakDays: 90, eolWarnDays: 180 },
  },
  {
    id: 'mariadb',
    name: 'MariaDB',
    category: 'runtime',
    vendor: 'MariaDB Foundation',
    blurb: '관계형 DB (MySQL 호환)',
    homepage: 'https://mariadb.org',
    icon: 'mariadb',
    eol: 'mariadb',
    policy: { minSoakDays: 90, eolWarnDays: 180 },
  },
  {
    id: 'mongodb',
    name: 'MongoDB',
    category: 'runtime',
    vendor: 'MongoDB Inc.',
    blurb: '도큐먼트 DB',
    homepage: 'https://www.mongodb.com',
    icon: 'mongodb',
    eol: 'mongodb',
    policy: { minSoakDays: 90, eolWarnDays: 180 },
  },
  {
    id: 'redis',
    name: 'Redis',
    category: 'runtime',
    vendor: 'Redis Ltd.',
    blurb: '인메모리 데이터 스토어',
    homepage: 'https://redis.io',
    icon: 'redis',
    eol: 'redis',
    repo: 'redis/redis',
  },
  {
    id: 'valkey',
    name: 'Valkey',
    category: 'runtime',
    vendor: 'Linux Foundation',
    blurb: 'Redis 오픈소스 포크',
    homepage: 'https://valkey.io',
    icon: 'valkey',
    eol: 'valkey',
    repo: 'valkey-io/valkey',
  },
  {
    id: 'kafka',
    name: 'Apache Kafka',
    category: 'runtime',
    vendor: 'ASF',
    blurb: '분산 이벤트 스트리밍',
    homepage: 'https://kafka.apache.org',
    icon: 'apachekafka',
    eol: 'apache-kafka',
    repo: 'apache/kafka',
    policy: { minSoakDays: 60, minPatch: 1 },
  },
  {
    id: 'rabbitmq',
    name: 'RabbitMQ',
    category: 'runtime',
    vendor: 'Broadcom',
    blurb: '메시지 브로커',
    homepage: 'https://www.rabbitmq.com',
    icon: 'rabbitmq',
    eol: 'rabbitmq',
    repo: 'rabbitmq/rabbitmq-server',
  },
  {
    id: 'nginx',
    name: 'nginx',
    category: 'runtime',
    vendor: 'F5',
    blurb: '웹 서버 / 리버스 프록시',
    homepage: 'https://nginx.org',
    icon: 'nginx',
    eol: 'nginx',
  },
  {
    id: 'haproxy',
    name: 'HAProxy',
    category: 'runtime',
    vendor: 'HAProxy Technologies',
    blurb: 'L4/L7 로드밸런서',
    homepage: 'https://www.haproxy.org',
    icon: 'haproxy',
    eol: 'haproxy',
    repo: 'haproxy/haproxy',
  },
  {
    id: 'minio',
    name: 'MinIO',
    category: 'runtime',
    vendor: 'MinIO Inc.',
    blurb: 'S3 호환 오브젝트 스토리지',
    homepage: 'https://min.io',
    icon: 'minio',
    repo: 'minio/minio',
    // 날짜 기반 릴리즈 태그 (RELEASE.2026-12-18T13-15-44Z)
    tagFilter: '^RELEASE\\.',
  },
];
